import {
  misskeyCheckMiAuth,
  missekyGetI,
  misskeyCreateReaction,
  misskeyDeleteReaction,
  misskeyCreateNote,
  misskeyGetEmojis,
  misskeyGetTimelineGlobal,
  misskeyGetTimelineHome,
  misskeyGetTimelineLocal,
  misskeyGetTimelineChannel,
  misskeyGetTimelineUserList,
  misskeyGetTimelineAntenna,
  misskeyGetTimelineHashtag,
  misskeyGetTimelineSearch,
  misskeyGetNoteReactions,
  misskeyGetNote,
  misskeyGetMeta,
  misskeyGetFollowedChannels,
  misskeyGetMyAntennas,
  misskeyGetUserLists,
} from "./misskey";

export const apiRequest = {
  ["misskey:checkMiAuth"]: misskeyCheckMiAuth,
  ["misskey:getI"]: missekyGetI,
  ["misskey:getEmojis"]: misskeyGetEmojis,
  ["misskey:getTimelineHome"]: misskeyGetTimelineHome,
  ["misskey:getTimelineLocal"]: misskeyGetTimelineLocal,
  ["misskey:getTimelineGlobal"]: misskeyGetTimelineGlobal,
  ["misskey:getTimelineChannel"]: misskeyGetTimelineChannel,
  ["misskey:getTimelineList"]: misskeyGetTimelineUserList,
  ["misskey:getTimelineAntenna"]: misskeyGetTimelineAntenna,
  ["misskey:getTimelineHashtag"]: misskeyGetTimelineHashtag,
  ["misskey:getTimelineSearch"]: misskeyGetTimelineSearch,
  ["misskey:createReaction"]: misskeyCreateReaction,
  ["misskey:deleteReaction"]: misskeyDeleteReaction,
  ["misskey:getNoteReactions"]: misskeyGetNoteReactions,
  ["misskey:getNote"]: misskeyGetNote,
  ["misskey:getMeta"]: misskeyGetMeta,
  ["misskey:createNote"]: misskeyCreateNote,
  ["misskey:getFollowedChannels"]: misskeyGetFollowedChannels,
  ["misskey:getMyAntennas"]: misskeyGetMyAntennas,
  ["misskey:getUserLists"]: misskeyGetUserLists,
};
